### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by freshkitty** [Blubberboy333/SkyBlock#1]
????
Just No Idea

[CrashDump_Tue_May_10-23.55.55-EDT_2016.zip](https://github.com/Blubberboy333/SkyBlock/files/258541/CrashDump_Tue_May_10-23.55.55-EDT_2016.zip)

**Comment by Blubberboy333** [comment]
Thanks, i'll fix this when i get home

**Comment by freshkitty** [comment]
U fix it?
Also just wondering, is there a method to protect each person's island?

**Comment by Blubberboy333** [comment]
I just updated it, and there's currently no way to protect someone's island
