### ISSUE TITLE
Island creating  not worked

### ISSUE THREAD

**Issue by Taytan9912** [Blubberboy333/SkyBlock#2]
When i use /is create then my island don't respond and i fell down under world

**Comment by Blubberboy333** [comment]
This is a bug that happens every now and then. If this occurs, delete the island by running the command "/is delete" and make a new one

**Comment by Taytan9912** [comment]
Ok i see, but islands creating too close to others islands

**Comment by Blubberboy333** [comment]
Unfortunately, there isn't a way to prevent islands from spawning near each other

**Comment by Gamecrafter** [comment]
@Blubberboy333 It's your code. Blame yourself. :stuck_out_tongue:

**Comment by doducquang** [comment]
nice plugin but please fix :P

**Comment by Blubberboy333** [comment]
I'm working on it :)
